name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: List build output
        run: ls -la dist/

      - name: Debug Token
        run: |
          echo "Token length: ${#NETLIFY_AUTH_TOKEN}"
          echo "Token starts with: ${NETLIFY_AUTH_TOKEN:0:10}..."
          echo "Testing Netlify API access..."
          curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
               -H "Content-Type: application/json" \
               "https://api.netlify.com/api/v1/sites/1adc4bfc-1965-4bc2-936c-b0b257a01b99" \
               -w "\nHTTP Status: %{http_code}\n" \
               -s
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy to Netlify
        run: |
          echo "Installing Netlify CLI..."
          npm install -g netlify-cli@latest
          echo "Deploying to Netlify..."
          netlify deploy --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=1adc4bfc-1965-4bc2-936c-b0b257a01b99 --prod --timeout=600
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}