

# Staging Deployment Workflow
name: Deploy to Staging

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create .npmrc file
        run: echo "legacy-peer-deps=true" > .npmrc

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: List installed packages (debug)
        run: npm list react-tilt || echo "react-tilt not found"

      - name: Check node_modules (debug)
        run: ls -la node_modules/ | grep react-tilt || echo "react-tilt directory not found"

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: ls -la dist/

      - name: Deploy Preview to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy preview for ${{ github.head_ref || github.ref_name }}"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}